#!/bin/bash

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install docker.io
sudo apt-get -y install docker-compose

#update IP Tables
mkdir /etc/systemd/system/docker.service.d
cat << EOF > /etc/systemd/system/docker.service.d/noiptables.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --iptables=false
EOF
systemctl daemon-reload

#Add user to docker
sudo usermod -aG docker rtadmin

#Install Webmin
wget http://prdownloads.sourceforge.net/webadmin/webmin_1.860_all.deb
dpkg --install webmin_1.860_all.deb
sudo apt-get install -y -f

#Install Shorewall
sudo apt-get install -y shorewall

cp etc/shorewall/* /etc/shorewall/
sudo service shorewall start

#Add pqzone to Docker
docker network create --subnet=172.18.0.0/24 --gateway=172.18.0.100 --ip-range=1                                        72.18.0.2/24 -o "com.docker.network.bridge.name"="dkzone" dkzone

#Install Zip
sudo apt-get install -y zip tree unzip links2